# Generated by Django 4.0.5 on 2022-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackGroud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='HomeBackGroud anun')),
                ('name2', models.CharField(max_length=20, null=True, verbose_name='HomeBackGroud anun2')),
                ('about', models.TextField(null=True, verbose_name='HomeBackGroud about')),
                ('img', models.ImageField(null=True, upload_to='media', verbose_name='HomeBackGroud img')),
            ],
            options={
                'verbose_name': 'HomeBackGroud',
                'verbose_name_plural': 'HomeBackGrouds',
            },
        ),
    ]
