# Generated by Django 4.0.5 on 2022-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackGroud2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='HomeBackGroud2 anun')),
                ('about', models.TextField(verbose_name='HomeBackGroud2 about')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeBackGroud2 img')),
            ],
            options={
                'verbose_name': 'HomeBackGroud2',
                'verbose_name_plural': 'HomeBackGroud2s',
            },
        ),
    ]
