# Generated by Django 4.0.5 on 2022-06-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_arkacayinturizm_delete_homebackgroud2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kayqimasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kayqimasin anun')),
                ('about', models.TextField(verbose_name='Kayqimasin about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Kayqimasin img')),
            ],
            options={
                'verbose_name': 'Kayqimasin',
                'verbose_name_plural': 'Kayqimasin',
            },
        ),
    ]
