# Generated by Django 4.0.5 on 2022-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kayqimasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kayqimasindetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Kayqimasindetal anun')),
                ('about', models.TextField(verbose_name='Kayqimasindetal about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Kayqimasindetal img')),
            ],
            options={
                'verbose_name': 'Kayqimasindetal',
                'verbose_name_plural': 'Kayqimasindetal',
            },
        ),
        migrations.AlterField(
            model_name='kayqimasin',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Kayqimasin anun'),
        ),
    ]
