# Generated by Django 4.0.5 on 2022-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kayqimasindetal_alter_kayqimasin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayqimasindetal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kayqimasindetal anun'),
        ),
    ]
