# Generated by Django 4.0.5 on 2022-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_kayqimasindetal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='apranqnervacharvox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='apranqi anun')),
                ('gin', models.IntegerField(verbose_name='aparanqi gin')),
                ('img', models.ImageField(upload_to='media', verbose_name='apranqi nkar')),
            ],
            options={
                'verbose_name': 'apranq',
                'verbose_name_plural': 'apranqner',
            },
        ),
    ]
