# Generated by Django 4.0.5 on 2022-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_apranqnervacharvox'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='aboutus anun')),
                ('about', models.TextField(verbose_name='aboutus about')),
                ('img', models.ImageField(upload_to='media', verbose_name='aboutus img')),
            ],
            options={
                'verbose_name': 'aboutus',
                'verbose_name_plural': 'aboutuss',
            },
        ),
        migrations.DeleteModel(
            name='Kayqimasindetal',
        ),
    ]
