# Generated by Django 4.0.5 on 2022-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blokej2'),
    ]

    operations = [
        migrations.CreateModel(
            name='blokej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='blog anun')),
                ('img', models.ImageField(upload_to='media', verbose_name='blog nkar')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
