# Generated by Django 4.0.5 on 2022-06-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blokej'),
    ]

    operations = [
        migrations.CreateModel(
            name='hyuranoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='hyuranoci anun')),
                ('about', models.TextField(verbose_name='hyuranoci about')),
                ('img', models.ImageField(upload_to='media', verbose_name='hyuranoci img')),
            ],
            options={
                'verbose_name': 'hyuranoc',
                'verbose_name_plural': 'hyuranocner',
            },
        ),
        migrations.AlterModelOptions(
            name='blokej2',
            options={'verbose_name': 'blog2', 'verbose_name_plural': 'blog2s'},
        ),
        migrations.AlterField(
            model_name='blokej2',
            name='about',
            field=models.TextField(verbose_name='blog2 about '),
        ),
        migrations.AlterField(
            model_name='blokej2',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='blog2 nkar'),
        ),
        migrations.AlterField(
            model_name='blokej2',
            name='name',
            field=models.CharField(max_length=100, verbose_name='blog2 anun'),
        ),
    ]
