# Generated by Django 4.0.5 on 2022-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_hyuranoc_alter_blokej2_options_alter_blokej2_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hajortvayr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='hajort vayri anun')),
                ('about', models.TextField(verbose_name='hajort vayri about')),
                ('img', models.ImageField(upload_to='media', verbose_name='hajort vayri img')),
            ],
            options={
                'verbose_name': 'hajort vayr',
                'verbose_name_plural': 'hajort vayrer',
            },
        ),
    ]
