# Generated by Django 4.0.5 on 2022-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_arkacayinturizm_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Login img')),
            ],
        ),
    ]
