# Generated by Django 4.0.5 on 2022-06-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_loginimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginimg',
        ),
    ]
