# Generated by Django 4.0.5 on 2022-06-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_loginimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebackgroud',
            name='text',
            field=models.TextField(null=True, verbose_name='HomeBackGroud text detali hamar'),
        ),
    ]
