# Generated by Django 4.0.5 on 2022-06-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_homebackgroud_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='staysej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='stays eji2 anun')),
                ('img', models.ImageField(upload_to='media', verbose_name='stays eji2 nkar')),
                ('about', models.TextField(verbose_name='stays ejii2 about')),
            ],
            options={
                'verbose_name': 'stays2',
                'verbose_name_plural': 'stayss2',
            },
        ),
    ]
